pipeline {
    agent any

    environment {
        IMAGE_NAME = "yatindra-krishna/node-app"
        PORT = "5173"
    }

    stages {
        stage('Checkout Code') {
            steps {
                script {
                    git url: "https://github.com/yatindra-krishna/Liaplus-ai.git", branch: "main"
                }
            }
        }

        stage('Run Container') {
            steps {
                sh "cd react-todo/ && docker-compose down && docker-compose up -d"
            }
        }

        // Updated SonarQube Analysis Stage
        stage('SonarQube Analysis') {
            environment {
                SONAR_URL = "http://98.70.55.30:9000/"
            }
            steps {
                withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
                    sh 'cd react-todo/ && mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}'
                }
            }
        }
    }

    post {
        success {
            echo "Deployment Successful!"
        }
        failure {
            echo "Build Failed!"
        }
    }
}
